image: archlinux
packages: 
  - oss-cad-suite-build-bin
sources: 
  - https://git.sr.ht/~sajattack/yo6530
tasks:
  - build: |
      source /opt/oss-cad-suite/environment
      cd yo6530
      make MCS6530_002=1
      truncate -s 128K build/mcs6530_002.bin
      make MCS6530_003=1
      truncate -s 128K build/mcs6530_003.bin

artifacts: 
  - yo6530/build/mcs6530_002.bin
  - yo6530/build/mcs6530_003.bin
