[build]
target = "avr-specs/avr-atmega2560.json"

[target.'cfg(target_arch = "avr")']
rustflags = "-Cpanic=abort"
runner = "ravedude mega2560 -cb 115200 -P /dev/ttyUSB0"

[unstable]
build-std = ["panic_abort", "core", "alloc"]
